#!/usr/bin/env node
// Generates FEASIBILITY.md from spikes/F*/thresholds.json and result.json. Never hand-edit the
// output: a hand-edited status is how a green dashboard stops meaning anything.
//
//   node scripts/feasibility.mjs                       rewrite FEASIBILITY.md
//   node scripts/feasibility.mjs --report-regressions  open an issue for pass -> fail
//
// thresholds.json is written before the spike runs:
//   { "test": "F1", "name": "...", "threshold": "50/50 sampled txs correct on every wallet",
//     "checkpoint": "CP1", "written": "2026-09-25", "existential": true }
// result.json is written by the spike:
//   { "pass": true, "measured": "50/50 on 5 wallets, P&L within 0.4%", "date": "...",
//     "commit": "...", "notes": "..." }

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

const read = (p) => (existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null)

// Sub-spikes sit one level down, because the board puts them where the task's Touches line says.
// T-F05b owns `spikes/F5/route-size/`, and a scan of `spikes/F*` alone never saw it: the spike ran,
// passed, wrote its result, and was invisible in the table this file generates. A spike nobody can
// see in FEASIBILITY.md is a spike that did not happen, as far as a checkpoint is concerned.
const spikeDirs = (parent) =>
  readdirSync(parent, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => `${parent}/${e.name}`)
    .filter((d) => existsSync(`${d}/thresholds.json`))

const spikes = existsSync('spikes')
  ? readdirSync('spikes')
      .filter((d) => /^F\d+$/.test(d))
      .sort((a, b) => Number(a.slice(1)) - Number(b.slice(1)))
      .flatMap((d) => [`spikes/${d}`, ...spikeDirs(`spikes/${d}`)])
      .filter((d) => existsSync(`${d}/thresholds.json`))
  : []

const rows = spikes.map((dir) => {
  const t = read(`${dir}/thresholds.json`) ?? {}
  const r = read(`${dir}/result.json`)
  return {
    // The id comes off thresholds.json, so a sub-spike reads as F5b rather than as its directory.
    id: t.test ?? dir.split('/').pop(),
    name: t.name ?? '',
    threshold: t.threshold ?? 'NOT WRITTEN DOWN',
    checkpoint: t.checkpoint ?? '',
    existential: t.existential === true,
    status: r === null ? 'not run' : r.pass === true ? 'pass' : 'FAIL',
    measured: r?.measured ?? '',
    date: r?.date ?? '',
    commit: (r?.commit ?? '').slice(0, 8),
  }
})

const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ')

const md = [
  '# FEASIBILITY.md',
  '',
  '**Generated by `scripts/feasibility.mjs`. Never hand-edit this file.** A hand-edited status is',
  'how a green dashboard stops meaning anything.',
  '',
  'A component is feasible only when a spike has run against real chain data and hit a number',
  'written down before the spike started. Vendor docs, a working happy path and "it should work"',
  'do not count. "Pass" means the measured number met the threshold on **every** listed input, not',
  'on average.',
  '',
  // No generation timestamp. It would say when this script ran, not when any spike ran, and it
  // would make the output differ on every run, so CI could never tell a stale file from a fresh
  // one. Each row carries its own date and commit, which is the honest answer.
  '',
  '| Test | What it proves | Threshold, written before the run | Measured | Status | CP | Commit |',
  '|---|---|---|---|---|---|---|',
  ...rows.map(
    (r) =>
      `| ${r.id}${r.existential ? ' **(existential)**' : ''} | ${cell(r.name)} | ${cell(r.threshold)} | ` +
      `${cell(r.measured) || '-'} | ${r.status === 'pass' ? 'pass' : r.status === 'FAIL' ? '**FAIL**' : 'not run'} | ` +
      `${r.checkpoint} | ${r.commit || '-'} |`,
  ),
  '',
  `${rows.filter((r) => r.status === 'pass').length} of ${rows.length} passing, ` +
    `${rows.filter((r) => r.status === 'FAIL').length} failing, ` +
    `${rows.filter((r) => r.status === 'not run').length} not run.`,
  '',
  'A failing test is not debated when it fails. It is decided at the next checkpoint, one of: keep,',
  'fallback, cut, or extend once with a new date. An undecided test at a checkpoint defaults to its',
  'fallback. The decision and its reason go in the PRD Decisions log the same day.',
  '',
].join('\n')

if (!process.argv.includes('--report-regressions')) {
  const prev = existsSync('FEASIBILITY.md') ? readFileSync('FEASIBILITY.md', 'utf8') : ''
  writeFileSync('FEASIBILITY.md', md)
  console.log(`feasibility: ${rows.length} spike(s) written${prev === md ? ', unchanged' : ''}.`)
  process.exit(0)
}

// A regression nobody is told about is the same as no test at all. One issue per newly failing test.
let previous = ''
try {
  previous = execFileSync('git', ['show', 'HEAD~1:FEASIBILITY.md'], { encoding: 'utf8' })
} catch {
  console.log('feasibility: no previous FEASIBILITY.md to compare, nothing to report.')
  process.exit(0)
}

const regressed = rows.filter(
  (r) => r.status === 'FAIL' && new RegExp(`\\| ${r.id}\\b[^\\n]*\\| pass \\|`).test(previous),
)

for (const r of regressed) {
  const title = `${r.id} regressed: ${r.name || 'feasibility test'} now fails`
  const body = [
    `\`${r.id}\` passed on the previous nightly run and fails now.`,
    '',
    `- Threshold, written before the first run: ${r.threshold}`,
    `- Measured this run: ${r.measured || 'see spikes/' + r.id + '/result.json'}`,
    `- Commit: ${r.commit}`,
    r.existential
      ? '- **This test is existential.** If it has no workable fallback, the scope changes.'
      : '',
    '',
    'Do not debate this here. Bring the raw output to the next checkpoint and decide one of: keep,',
    'fallback, cut, extend once. Undecided at the checkpoint defaults to the fallback.',
  ]
    .filter(Boolean)
    .join('\n')

  execFileSync(
    'gh',
    ['issue', 'create', '--title', title, '--body', body, '--label', 'feasibility'],
    {
      stdio: 'inherit',
    },
  )
}

console.log(`feasibility: ${regressed.length} regression(s) reported.`)
